name: Node Auth Application Pipeline

# Trigger the workflow
on:
  push:
    branches:
      - '**' # Matches every branch for push events
  pull_request:
    branches:
      - '**' # Matches every branch for pull request events

jobs:
  # Step: Cache and Install Dependencies
  npm:
    uses: SAINIAbhishek/shared-workflows/.github/workflows/cache-install-dependencies.yml@main
    with:
      node-version: '20.17.0'
      lock-file: 'package-lock.json'
      cache-path: 'node_modules'
      cache-key-prefix: 'auth'
      working-directory: './'
